### ISSUE TITLE
Host: 11.1 is not greater than target: 11.1-RELEASE

### ISSUE THREAD

**Issue by benw2** [iocage/iocage#354]
When selecting the release from the command line, the following error is received : 

```
root@vbox-zfs:/tmp/iocage # iocage fetch -h -r 11.1-RELEASE

Host: 11.1 is not greater than target: 11.1-RELEASE

root@vbox-zfs:/tmp/iocage # iocage --version
Version 0.9.9.2 ALPHA

```

This wasn't happening previously on the version in the ports (py36-iocage), which is version 0.9.8 from memory.

Can fetch 11.1-RELEASE from the install menu, and that works fine, but couldn't get it working directly from the CLI.

**Comment by skarekrow** [comment]
This was actually fixed in https://github.com/iocage/iocage/commit/9009b6ae54cc8651fba892f7d991d1e8457c74d1

**Comment by benw2** [comment]
Still happening here - looks like the config file is picking up the -Px patch on the release, which appears to be upsetting the split for the version comparison. Not sure where this is being extracted from.

I just built a new FBSD 11.1 release, and it's got a release of 11.1-RELEASE-p1 from somewhere : 

```
root@vbox-zfs:/iocage/jails/template-111 # grep -i release config.json
    "cloned_release": "11.1-RELEASE",
    "release": "11.1-RELEASE-p1",
```

Which upsets the startup script, as it looks like it's just doing a split on the - 

```
root@vbox-zfs:~ # iocage start template-111

Host: 11.1 is not greater than jail: 11.1-RELEASE

```

Manually editing the release in the config.json file (stripping out the -p1) and everything works fine

```
/iocage/jails/template-111/config.json: 113 lines, 2978 characters.
root@vbox-zfs:~ # iocage start template-111
* Starting template-111
  + Started OK
  + Starting services OK

```

**Comment by skarekrow** [comment]
I still cannot reproduce on the latest code :/

```
╰─ iocage clean -jf
Cleaning iocage/jails
All iocage jail datasets have been destroyed.
╰─ iocage create -n template-111 -r 11.1-RELEASE
template-111 successfully created!
╰─ iocage start template-111
* Starting template-111
  + Started OK
  + Starting services OK
root@iocage:/iocage/jails/template-111 # grep -i release config.json
    "cloned_release": "11.1-RELEASE",
    "release": "11.1-RELEASE-p1",
root@iocage:~ # uname -a
FreeBSD iocage.home 11.1-RELEASE-p1 FreeBSD 11.1-RELEASE-p1 #0: Wed Aug  9 11:55:48 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by benw2** [comment]
Hmm yeah I can't replicate it this morning either... I blew away the VM and started again and it's not occurring anymore - must have been something funky happening at my end.

```
root@vbox-zfs:/usr/home # iocage create -n template-111 -r 11.1-RELEASE ip4_addr='lo1|172.16.1.4' allow_sysvipc=1 resolver=/dev/null host_hostname=template-111
********************************************************************************
fdescfs(5) is not mounted, performance may suffer. Please run:
mount -t fdescfs fdesc /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdesc /dev/fd  fdescfs  rw  0  0
********************************************************************************

template-111 successfully created!

```

Apologies for wasting your time.

**Comment by skarekrow** [comment]
You didn't waste my time :)

Glad everything's OK on your end now as well.
