### ISSUE TITLE
Cloning a jail is not working

### ISSUE THREAD

**Issue by DeeeeLAN** [iocage/iocage#557]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
```
# iocage --version
Version	1.0 ALPHA
```

- [x] Supply the commands used, along with any steps to recreate it.
```
# iocage clone XMRig --name XMRig2
```

- [x] Provide the output from the command you issued.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 207, in _create_jail
    f"@{jail_uuid}"], stderr=su.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['zfs', 'snapshot', '-r', 'pond/iocage/jails/XMRig@XMRig2']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/clone.py", line 64, in cli
    clone=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 644, in create
    exit_on_error=self.exit_on_error).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 86, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 209, in _create_jail
    raise RuntimeError(f"Jail: {jail_uuid} not found!")
RuntimeError: Jail: XMRig2 not found!
```

- [x] Supply what you expected the result or output to be
    I expected a jail to be cloned with the name XMRig2.

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.
    Unsure, running freenas which supplies 1.0 ALPHA, unable to manually update to master.

**Comment by yerrysherry** [comment]
# iocage --version
Version	1.0 ALPHA

# iocage create -r 11.2-RELEASE -n XMRig
XMRig successfully created

# iocage clone XMRig --name XMRig2
XMRig2 successfully cloned!

With me, it is working fine.

**Comment by theAlchemist-dev** [comment]
I have found a scenario where it does occur:

```
iocage clone apache -n apachetest
iocage start apachetest
iocage console apachetest
# Do some stuff
exit
iocage destroy apachetest
iocage clone apache -n apachetest
```

Then the message appears before me too:

> iocage clone apache -n apachetest
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 203, in _create_jail
>     f"@{jail_uuid}"], stderr=su.PIPE)
>   File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['zfs', 'snapshot', '-r', 'zfs-os/iocage/jails/apache@apachetest']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/iocage", line 10, in <module>
>     sys.exit(cli())
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/iocage/cli/clone.py", line 64, in cli
>     clone=True)
>   File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 643, in create
>     exit_on_error=self.exit_on_error).create_jail()
>   File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 85, in create_jail
>     return self._create_jail(jail_uuid, location)
>   File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 205, in _create_jail
>     raise RuntimeError(f"Jail: {jail_uuid} not found!")
> RuntimeError: Jail: apachetest not found!

It appears the destroy is not fully purging the jail?

**Comment by skarekrow** [comment]
This should be fixed by the recent destroy commits in 1.0 and 1.1. Closing

**Comment by martenlindblad** [comment]
Confirmed still not working for Version	1.1 RELEASE 2019/01 on 12.0-RELEASE-p10

**Comment by Marsel-marsel** [comment]
Also confirm that it's not working in ```iocage: Version 1.1 RELEASE 2019/01```. Seems that ```iocage destroy``` doesn't remove ZFS snapshot of the jail. WA is delete it using ```zfs``` ```sudo zfs destroy -r zroot/iocage/jails/<orig_jail>@<cloned_jail>```

**Comment by martenlindblad** [comment]
confirmed working with version 1.2.
