### ISSUE TITLE
iocage fetch --noverify still verifies SSL certs

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#88]
Running `iocage fetch` with `--novierfy` still fails with certificate verification:
```
root@rpi3:~/chunter/_build/default/lib/erltrace # iocage fetch --noverify
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 630, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 94, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 101, in fetch_cmd
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 182, in fetch_release
    eol = self.__fetch_eol_check__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 76, in __fetch_eol_check__
    req = requests.get(_eol)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
```

**Comment by skarekrow** [comment]
Looks like it's failing in the EOL check not on your supplied server. Can you please paste your command too.

**Comment by Licenser** [comment]
1st line: `iocage fetch --noverify`

**Comment by skarekrow** [comment]
D'oh! Ok well for the time being also append `--noeol` and I'll fix this next week :+1:

**Comment by Licenser** [comment]
Awesome `--noeol` does the trick :D thanks

**Comment by skarekrow** [comment]
Yay!

**Comment by totalAldo** [comment]
This is happening on one of my hosts:
```
# iocage --version
Version	0.9.10 ALPHA
```

```
# iocage fetch --noverify -r 11.1-RELEASE
Fetching: 11.1-RELEASE

Extracting: base.txz... 
Extracting: lib32.txz... 
Extracting: doc.txz... 

* Updating 11.1-RELEASE to the latest patch level... 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 158, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 943, in fetch
    **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 332, in fetch_release
    rel = self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 635, in fetch_ftp_release
    self.fetch_update()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 1017, in fetch_update
    with urllib.request.urlopen(f) as fbsd_update:
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

```

Same after trying:
`# iocage fetch --noverify --noeol -r 11.1-RELEASE`

**Comment by skarekrow** [comment]
`--noverify` is only for HTTP fetching, as the `--help` output shows:
```
  -V, --verify / -NV, --noverify  Enable or disable verifying SSL cert for
                                  HTTP fetching.
```
I can look into doing it for FTP, but open a new issue so I can mark it as a feature request :)

**Comment by totalAldo** [comment]
I tried to do due diligence and read that but didn't realize it was using HTTP.
The main issue is that the SSL verification is failing on the fetch. Its also preventing iocage update from working for jails on this one host so not sure if there's a config issue I should look at. Any pointers appreciated.

**Comment by skarekrow** [comment]
@totalAldo Oh it's fine, you found a very old issue instead of opening a new one, you certainly did due diligence :) I appreciate the effort.

I would verify the host has `ca_root_nss` installed

**Comment by totalAldo** [comment]
The host has ca_root_nss. I uninstalled it and checked that /usr/local/etc/ssl was empty, then reinstalled, still getting the SSL warning:

```
# pkg info|grep ca_root_nss
ca_root_nss-3.32.1             Root certificate bundle from the Mozilla Project
```

`# portmaster security/ca_root_nss`

```
# iocage fetch -r 11.1-RELEASE
Fetching: 11.1-RELEASE

Extracting: base.txz... 
Extracting: lib32.txz... 
Extracting: doc.txz... 

* Updating 11.1-RELEASE to the latest patch level... 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 158, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 943, in fetch
    **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 332, in fetch_release
    rel = self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 635, in fetch_ftp_release
    self.fetch_update()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 1017, in fetch_update
    with urllib.request.urlopen(f) as fbsd_update:
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

```

**Comment by skarekrow** [comment]
What about `py36-certifi`? Is that installed?
```
╰─ pkg info | grep "certifi"
ca_root_nss-3.32.1             Root certificate bundle from the Mozilla Project
py36-certifi-2017.7.27.1       Mozilla SSL certificates

```

**Comment by totalAldo** [comment]
indeed, reinstalled, and tried again, same result.

```
# pkg info|grep certifi
ca_root_nss-3.32.1             Root certificate bundle from the Mozilla Project
py36-certifi-2017.7.27.1       Mozilla SSL certificates
```

**Comment by skarekrow** [comment]
Are you using a proxy by chance? I'm out of ideas, I'd try the freebsd-questions mailing list, or jails and see what others suggest. If you find something that works, report back for time travelers who may stumble on this.

Another note, this is failing during the EOL check, so I'd try with just `--noeol` instead of with `--noverify`. Maybe @Licenser found a solution, as it seems you both stumbled on the same bug, but `--noverify --noeol` did not work for you, but did for him :/

**Comment by Licenser** [comment]
Sorry nope didn't find one but didn't tried recently either I ended up not using iocage.

**Comment by totalAldo** [comment]
Not using a proxy. 
Same results with:
`iocage fetch --noeol -r 11.1-RELEASE `

Will report back with any findings. Thanks again!

**Comment by skarekrow** [comment]
@totalAldo Ok so I found what I *think* is your issue, so at the very least you can sidestep the SSL verification until you figure out what's happening on that host. `--noverify` should now work for you to `fetch`. If this works for you, I'll add a `--noverify` flag to `update` as well.

**Comment by totalAldo** [comment]
unfortunately, still not working on this host with commit 60677694e08d8dadafa32fd19b837100ba3fccb2

`# iocage fetch --noverify -r 11.1-RELEASE`
produces certificate verify failed

**Comment by skarekrow** [comment]
Hmm, I'm wondering if GitHub redirects to HTTPS regardless. I'll try a different approach here, give me a few :)

**Comment by skarekrow** [comment]
@totalAldo Ok, https://github.com/iocage/iocage/commit/53830ac4c412c087c1b181a15649076618da2150 is yet another attempt :D Lemme know

**Comment by totalAldo** [comment]
well done :) beauty to my eyes:

```
# iocage fetch --noverify -r 11.1-RELEASE
Fetching: 11.1-RELEASE

Extracting: base.txz... 
Extracting: lib32.txz... 
Extracting: doc.txz... 

* Updating 11.1-RELEASE to the latest patch level... 
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching public key from update5.freebsd.org... done.
Fetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.
Fetching metadata index... done.
Fetching 2 metadata files... done.
Inspecting system... done.
Preparing to download files... done.
Fetching 4 patches... done.
Applying patches... done.

The following files will be updated as part of updating to 11.1-RELEASE-p2:
/bin/freebsd-version
/usr/sbin/hostapd
/usr/sbin/sshd
/usr/sbin/wpa_supplicant
Installing updates... done.

```

**Comment by skarekrow** [comment]
Phew! Ok, create a ticket to add `--noverify` to `update`, and I'll get that added sometime soonish :)
