### ISSUE TITLE
Can not delete/update mount point after moving iocage to different pool

### ISSUE THREAD

**Issue by skuzzle** [iocage/iocage#924]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

```
iocage --version
Version freeNAS 11.2-U3
```

Due to a dying hard drive, I need to rescue my jails onto a different pool. So I did the typical `zfs send | receive` stuff, but with an intermediate file (directly piping from send to receive always gave me Broken Pipe errors):
```
zfs snapshot -r media_1/iocage@XXX
zfs send -R media_1/iocage@XXX > iocage.backup
cat iocage.backup | zfs receive -vF media_2/iocage
iocage activate media_2
```

I was happy to see that my jails seemed to be rescued, but then I encountered an error with the jail's mount points. For example, a jail running the bind dns server:

```
iocage fstab -l bind
+-------+-------------------------------------------------------------------------------------------------------+
| INDEX |                                              FSTAB ENTRY                                              |
+=======+=======================================================================================================+
| 0     | /mnt/media_2/server_config/dns /mnt/media_1/iocage/jails/bind/root/usr/local/etc/namedb nullfs rw 0 0 |
+-------+-------------------------------------------------------------------------------------------------------+
```
As you can see, the mount point still points to the jail's previous location (...media_1...). Trying to update or deleting it always gives me:

```
iocage fstab -r bind 0
Destination: /mnt/media_1/iocage/jails/bind/root/usr/local/etc/namedb does not include jail's mountpoint! (/mnt/media_2/iocage/jails/bind/root)
```

Trying the same using the FreeNAS UI gives detailed stack traces:

```
Error: concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/middlewared/plugins/jail.py", line 707, in fstab
    dump, _pass, index=index
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1037, in fstab
    index=index
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fstab.py", line 69, in __init__
    self.dests = self.__validate_fstab__(self.fstab, 'all')
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_fstab.py", line 212, in __validate_fstab__
    exception=iocage_lib.ioc_exceptions.ValidationFailed
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 90, in logit
    _callback(content, exception)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_common.py", line 64, in callback
    raise callback_exception(message)
iocage_lib.ioc_exceptions.ValidationFailed: ["Destination: /mnt/media_1/iocage/jails/bind/root/usr/local/etc/namedb does not include jail's mountpoint! (/mnt/media_2/iocage/jails/bind/root)"]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.6/site-packages/middlewared/worker.py", line 128, in main_worker
    res = loop.run_until_complete(coro)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/middlewared/worker.py", line 88, in _run
    return await self._call(f'{service_name}.{method}', serviceobj, methodobj, params=args, job=job)
  File "/usr/local/lib/python3.6/site-packages/middlewared/worker.py", line 81, in _call
    return methodobj(*params)
  File "/usr/local/lib/python3.6/site-packages/middlewared/worker.py", line 81, in _call
    return methodobj(*params)
  File "/usr/local/lib/python3.6/site-packages/middlewared/schema.py", line 668, in nf
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/middlewared/plugins/jail.py", line 719, in fstab
    raise CallError(e.message)
middlewared.service_exception.CallError: [EFAULT] Destination: /mnt/media_1/iocage/jails/bind/root/usr/local/etc/namedb does not include jail's mountpoint! (/mnt/media_2/iocage/jails/bind/root)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 165, in call_method
    result = await self.middleware.call_method(self, message)
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 1141, in call_method
    return await self._call(message['method'], serviceobj, methodobj, params, app=app, io_thread=False)
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 1078, in _call
    return await self._call_worker(serviceobj, name, *args)
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 1105, in _call_worker
    job,
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 1036, in run_in_proc
    return await self.run_in_executor(self.__procpool, method, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 1021, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
middlewared.service_exception.CallError: [EFAULT] Destination: /mnt/media_1/iocage/jails/bind/root/usr/local/etc/namedb does not include jail's mountpoint! (/mnt/media_2/iocage/jails/bind/root)
```

I'm not really an expert on this whole ZFS and mounting stuff, so I'd apologize in advance in case I made some obvious mistakes.

**Comment by skarekrow** [comment]
This is an old bug that *should* be solved in 11.3, but may also be fixed in U4/5.  In the meantime you can fix this manually by editing /mnt/media_1/iocage/jails/bind/fstab and changing the mountpoints there

**Comment by skuzzle** [comment]
Thanks for your fast reply. Editing the file manually indeed worked. Now I'm still facing some further migration issues but those are not related to this ticket.
